/** Local Bhutanese AI / branded demo imagery served from /public/bhutan */
export const BHUTAN_IMAGES = {
  hero: "/bhutan/hero-market.webp",
  editorialDonate: "/bhutan/editorial-donate.webp",
  editorialMarket: "/bhutan/editorial-market.webp",
  profileBanner: "/bhutan/profile-banner.webp",
  profileAvatar: "/bhutan/profile-avatar.webp",
  categories: {
    Tops: "/bhutan/cat-tops.webp",
    Bottoms: "/bhutan/cat-bottoms.webp",
    Dresses: "/bhutan/cat-dresses.webp",
    Outerwear: "/bhutan/cat-outerwear.webp",
    Shoes: "/bhutan/cat-shoes.webp",
    Accessories: "/bhutan/cat-accessories.webp",
    Other: "/bhutan/cat-other.webp",
  },
  centers: {
    "thimphu-childrens-home": "/bhutan/center-thimphu-home.webp",
    "paro-youth-centre": "/bhutan/center-paro-youth.webp",
    "phuentsholing-shelter-hub": "/bhutan/center-pl-shelter.webp",
    "bhutan-youth-cso": "/bhutan/center-cso.webp",
  },
  listings: {
    denim: "/bhutan/listing-denim.webp",
    tee: "/bhutan/cat-tops.webp",
    hoodie: "/bhutan/listing-hoodie.webp",
    dress: "/bhutan/cat-dresses.webp",
    sneakers: "/bhutan/cat-shoes.webp",
    jacket: "/bhutan/cat-outerwear.webp",
    skirt: "/bhutan/cat-dresses.webp",
    sweater: "/bhutan/cat-tops.webp",
    pants: "/bhutan/cat-bottoms.webp",
    bag: "/bhutan/cat-accessories.webp",
    boots: "/bhutan/cat-shoes.webp",
    shirt: "/bhutan/cat-tops.webp",
    coat: "/bhutan/listing-coat.webp",
    shorts: "/bhutan/cat-bottoms.webp",
    scarf: "/bhutan/listing-scarf.webp",
    kids: "/bhutan/listing-kids.webp",
  },
} as const;
